### ISSUE TITLE
朋友圈点赞样式变化了

### ISSUE THREAD

**Issue by kxdsdnf** [TransparentLC/WechatMomentScreenshot#10]
现在朋友圈里点赞不显示用户头像了，显示的是用户的昵称

**Comment by TransparentLC** [comment]
如果是从“发现”点进朋友圈的信息流的话显示的是昵称，如果是点某位的头像来看他的朋友圈显示的就是头像。生成的截图对应的是后者😂

再说如果要显示昵称的话我从哪里找这么多昵称啊……（摊手
