### ISSUE TITLE
看看这个集赞，操作起来好像很方便。

### ISSUE THREAD

**Issue by iseeyou** [TransparentLC/WechatMomentScreenshot#11]
https://a.wejizan.ink/
微信里面打开不用注册。利用截图生成，更逼真。
使用了一下感觉不错。超过50赞要收费

**Comment by iseeyou** [comment]
http://pic.northernlights.ink/jizanshenqi/a.wejizan.cn.jpg

上面是二维码，微信扫一扫

**Comment by TransparentLC** [comment]
已经有不少人提过这个东西了～说一下我对这个的想法：
* 生成截图**需要登录注册**，不能算“方便”
* 在微信中打开会**触发微信登录**，但是生成截图实际上根本不需要获取任何真实微信用户的信息，我也**不想提供此类信息**
* 我做这个小工具是为了对抗滥用朋友圈（例如被迫在朋友圈发小广告）的不良风气，所以我不会在小工具中添加需要付费才能使用的功能
* 同类的工具当然不止我这一个，运行原理不一样，效果也会不一样，自己觉得哪个好用就用哪个咯～随便啦(`ヮ´ )
