### ISSUE TITLE
生成的头像区域有空白

### ISSUE THREAD

**Issue by yuanlinhu00** [TransparentLC/WechatMomentScreenshot#12]

**Comment by Thvrudorv** [comment]
我也有出现这个问题，而且基本上每次都会有空白

**Comment by TransparentLC** [comment]
有截图之类的吗～我试一下能不能复现这个问题



---原始邮件---
发件人: "Thvrudorv"<notifications@github.com&gt;
发送时间: 2020年9月11日(星期五) 凌晨0:31
收件人: "TransparentLC/WechatMomentScreenshot"<WechatMomentScreenshot@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: Re: [TransparentLC/WechatMomentScreenshot] 生成的头像区域有空白 (#12)




 
我也有出现这个问题，而且基本上每次都会有空白

**Comment by Thvrudorv** [comment]
> 有截图之类的吗～我试一下能不能复现这个问题
> […](#)
> ---原始邮件--- 发件人: "Thvrudorv"<notifications@github.com&gt; 发送时间: 2020年9月11日(星期五) 凌晨0:31 收件人: "TransparentLC/WechatMomentScreenshot"<WechatMomentScreenshot@noreply.github.com&gt;; 抄送: "Subscribed"<subscribed@noreply.github.com&gt;; 主题: Re: [TransparentLC/WechatMomentScreenshot] 生成的头像区域有空白 (#12) 我也有出现这个问题，而且基本上每次都会有空白 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

<img width="421" alt="截屏2020-09-11 下午3 50 47" src="https://user-images.githubusercontent.com/46417988/92886960-b5034580-f446-11ea-942a-d784a41bac8b.png">
嗯我估计是头像图床的问题

**Comment by TransparentLC** [comment]
已更换图床，可以 <kbd>Ctrl+F5</kbd> 刷新缓存再试一下？

之前的图床有部分图片没有了 Access-Control-Allow-Origin 响应头，因此就空白了|ー` )
