### ISSUE TITLE
2020-8-31 canvas报错

### ISSUE THREAD

**Issue by AC-Dawn** [TransparentLC/WechatMomentScreenshot#13]
原始在线使用
试图解析公众号链接：https://mp.weixin.qq.com/s/l1iXbTr8sNQHdqEF8aC55w  失败

后下载code切本地，填写公众号url及上传图片

测试全默认状态下生成，线上、离线环境：均报以下错误
SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

**Comment by TransparentLC** [comment]
![](https://user-images.githubusercontent.com/47057319/91698202-ebb6a180-eba4-11ea-8cfd-0284e59df3b1.png)

不能复现……

这个是画布污染问题，不过我确定生成截图的部分用的图片等等都有 `Access-Control-Allow-Origin: *`，还有一种可能是某些浏览器扩展会在网页上添加 CSS 样式导致跨域，用没有加载扩展的浏览器环境试试看？

**Comment by AC-Dawn** [comment]
确实，我重下了纯净版chrome测试也不行，但是换我同事的电脑就行了
迷惑，只能在我电脑上无限复现Orz
谢谢作者大大，回复神速

以及补一下，离线状态下默认参数报错图
![image](https://user-images.githubusercontent.com/19706924/91700732-e52a2900-eba8-11ea-8988-a706a7dabf84.png)

**Comment by TransparentLC** [comment]
我这里其实也会出这个问题……不过提示是 `SecurityError: CSSStyleSheet.cssRules getter: Not allowed to access cross-origin stylesheet`，应该是同一个问题。F12 的话可以看到 `<head>` 里面被塞了一个 `<style id="随机GUID">.pb-toast-main { ... } ...</style>`，我没找出是哪个扩展塞进来的，删掉这个 `<style>` 就没事了。

**Comment by AC-Dawn** [comment]
我在head和header里都没找到这个对应的style，直接全局搜也没有
眼神失去高光.jpg

**Comment by TransparentLC** [comment]
找了一下，确定了我这里被塞的那个 CSS 来自于油猴脚本[“弹窗阻止程序脚本”](https://greasyfork.org/zh-CN/scripts/395170-popup-blocker-script)

另外没什么别的问题的话这个 Issue 就先关了(=ﾟωﾟ)=
