### ISSUE TITLE
点赞数加个限制吧

### ISSUE THREAD

**Issue by pibigstar** [TransparentLC/WechatMomentScreenshot#16]
太高的话你服务可能会崩溃

**Comment by TransparentLC** [comment]
截图是使用JS在前端生成的，不需要用到后端，所以点赞数设得太多实际上可能崩溃的是浏览器&nbsp;(=ﾟωﾟ)=



---原始邮件---
发件人: "派大星"<notifications@github.com&gt;
发送时间: 2020年9月21日(星期一) 晚上8:24
收件人: "TransparentLC/WechatMomentScreenshot"<WechatMomentScreenshot@noreply.github.com&gt;;
抄送: "Subscribed"<subscribed@noreply.github.com&gt;;
主题: [TransparentLC/WechatMomentScreenshot] 点赞数加个限制吧 (#16)




 
太高的话你服务可能会崩溃

**Comment by pibigstar** [comment]
秀啊，我以为头像要从后端获取😂
