### ISSUE TITLE
字体颜色问题

### ISSUE THREAD

**Issue by yupenggit** [TransparentLC/WechatMomentScreenshot#18]
朋友圈输入纯数字会变成蓝色的超链接？希望能设置字体颜色

**Comment by TransparentLC** [comment]
字体颜色当然只有白底黑字了233

iOS 有个功能是自动把电话号码（也属于纯数字）转换为超链接，如果你也是**在 iOS 上使用**就会有这个问题的话我在网页上加一个 `<meta name="format-detection" content="telephone=no">` 应该可以修复。
