### ISSUE TITLE
希望添加ios版本的背景图

### ISSUE THREAD

**Issue by qiexiacn** [TransparentLC/WechatMomentScreenshot#19]
根据用户需求反馈部分iOS手机生成的时候表示显示电量图标之类的不好掩饰

**Comment by haolonghu** [comment]
ios！

**Comment by TransparentLC** [comment]
因为我现在手上也没有 iOS 设备，所以没办法做到和 iOS 一模一样的通知栏（摊手）

有那个需求的话，可以先自己准备一个 iOS 通知栏的图然后覆盖到生成的截图上……

**Comment by haolonghu** [comment]
我有
