### ISSUE TITLE
朋友圈话题不会变蓝

### ISSUE THREAD

**Issue by FreyFei** [TransparentLC/WechatMomentScreenshot#21]

**Comment by TransparentLC** [comment]
因为一直固定使用很旧的 7.x 版本所以完全没有意识到这东西的存在……(・ー・)

只要是正文中出现了 # 开头的东西（确切来说应该是符合 [`/(?:^|\s)(#\S+)(?:$|\s)/`](https://jex.im/regulex/#!flags=&re=(%3F%3A%5E%7C%5Cs)(%23%5CS%2B)(%3F%3A%24%7C%5Cs)) 的部分的第一组）都算是话题吗？

**Comment by WANGJUNHAOmatt** [comment]
同求此功能

**Comment by TransparentLC** [comment]
![](https://user-images.githubusercontent.com/47057319/136138092-13c271f1-4adb-4a6d-8983-03901fd4e2d5.png)
已添加～
