### ISSUE TITLE
设置好后点击生成没反应，换了浏览器也一样

### ISSUE THREAD

**Issue by Spectatorz** [TransparentLC/WechatMomentScreenshot#22]
如图

**Comment by TransparentLC** [comment]
图呢（

另外我不能复现这个 bug

**Comment by Spectatorz** [comment]
不好意思，我又重新用手机浏览器登入网址就一切正常了，电脑浏览器我怀疑可能是被广告拦截插件给拦截掉了

**Comment by Spectatorz** [comment]
> 图呢（
> 
> 另外我不能复现这个 bug

不好意思，我后来重新用手机浏览器登入网址就一切正常了，电脑浏览器反复测试都不行，我觉得有可能是被广告拦截插件拦截掉了，等下次使用的时候我测试一下

**Comment by TransparentLC** [comment]
因为没有后续回复所以先 close 了 (=ﾟωﾟ)=
