### ISSUE TITLE
建议增加点赞人头像,生成的图片有人问 我点了赞怎么没看到我点的

### ISSUE THREAD

**Issue by DarkLightest** [TransparentLC/WechatMomentScreenshot#23]

**Comment by TransparentLC** [comment]
因为集赞的营销号一般不会在意点赞的是哪些人，所以这里的头像都是随机抽取的，而且并没有支持手动选择头像的打算……

有这种要求的话，还是自己一个个下载**真实好友的头像**然后再 P 到对应的位置上吧 2333（但是怎么看都有点麻烦）
