### ISSUE TITLE
本地clone下来，打开index.html，在浏览器中无法生成图片，报错如下图所示

### ISSUE THREAD

**Issue by NickEric** [TransparentLC/WechatMomentScreenshot#24]
谷歌浏览器 和 Edge浏览器 报错一样
![image](https://user-images.githubusercontent.com/68672695/101591104-af59d380-3a26-11eb-8b63-73de1e632313.png)
报错信息为：SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

**Comment by TransparentLC** [comment]
发现是表情图（比如那些小黄脸）的图床不支持 CORS 了，已更换～

重新 clone 之后清除浏览器缓存再试试看？

**Comment by guobinAndroid** [comment]
> 发现是表情图（比如那些小黄脸）的图床不支持 CORS 了，已更换～
> 
> 重新 clone 之后清除浏览器缓存再试试看？

这个问题还在。

**Comment by TransparentLC** [comment]
刚刚试了一下，如果是 clone 的话我估计你是直接双击 index.html 打开的，这种情况下 URL 里会写着 `file://...` 于是会产生各种跨域问题，在 clone 后的文件夹用 `python -m http.server` 之类的东西开一个 HTTP 服务这样使用就不会有 SecurityError 了。

**Comment by TransparentLC** [comment]
因为没有后续回复所以先 close 了 (=ﾟωﾟ)= 如果还有问题可以再开 issue。
