### ISSUE TITLE
如果浏览器装了CanvasFingerprintBlock插件就无法看到生成的图片

### ISSUE THREAD

**Issue by Jasmine-liang** [TransparentLC/WechatMomentScreenshot#25]
装这个插件目的是保护隐私。我看了这个插件的原理，它block 源码中`var dURL = canvas.toDataURL();` 的 toDataURL() 函数。目的是防止网站从生成的canvas中收集用户的数据。参考：[https://chrome.google.com/webstore/detail/canvasfingerprintblock/ipmjngkmngdcdpmgmiebdmfbkcecdndc](url)
![image](https://user-images.githubusercontent.com/63624438/101784957-21b9d900-3b37-11eb-89b1-3b531486a379.png)

**Comment by Jasmine-liang** [comment]
![image](https://user-images.githubusercontent.com/63624438/101784901-14045380-3b37-11eb-9d47-81c156b168a9.png)

**Comment by TransparentLC** [comment]
然而 html2canvas 这个库的原理就是模拟绘制 DOM 的内容到 canvas 上，所以要让生成的图片可以保存的话必须这么做，并没有收集用户指纹的意思 2333

canvas 转图片 URL 也有 `URL.createObjectURL(canvas.toBlob())` 的做法，而且显然比 `canvas.toDataURL()` 更好，但是这样得到的图片 URL 在微信里似乎无法长按保存，所以还是选了后者。
