### ISSUE TITLE
关于微信表情输入和时间调节的问题

### ISSUE THREAD

**Issue by AdorableStar** [TransparentLC/WechatMomentScreenshot#3]
首先是微信表情，某些微信表情可以输入并生成在正文内，比如[奸笑][皱眉]，但是有些还是不行比如[强壮]，还有就是emoji的输入在电脑上的输入的emoji和手机上的emoji样式不一样，望修复。然后是请问能否加入调节截图时间的功能。然后不仅能调发布时间也能调截图时间。谢谢

**Comment by TransparentLC** [comment]
![](https://ae01.alicdn.com/kf/HTB11UMhXfWG3KVjSZPc762kbXXaU.png)

然而我输入[强壮]确实没看到表情啊～┓( ´∀` )┏

微信里的Emoji是以iOS的样式显示的，如果在其它系统（Windows/Android）使用这个小工具的话Emoji是按照各自的系统的样式显示，所以和微信里面显示的不一样，我试试看能不能在生成时全部替换成iOS的那种Emoji图片吧\_(:зゝ∠)\_

设置截图时间的功能已经加上了|ω•`)

**Comment by AdorableStar** [comment]
Wow！小透明大大真的是太棒了！不知道为啥你不喜欢用7.X的微信？7.X的微信有新功能耶！虽然我微信升了7.x之后进场卡死QAQ。要是能有7.x版本的截图就更好惹！By the way!进了大学发现，我的微信再也不是我的微信惹இ௰இ。

**Comment by TransparentLC** [comment]
因为我对视频动态什么的没兴趣啦（头像和昵称旁边的小蓝点简直神烦(╯‵□′)╯︵┻━┻
而且也没有什么人可以聊天所以强提醒也用不着2333
7.x的界面打算等到张小龙学会做产品了~~或者我心情好的时候~~再加～

就算进了大学我也不在朋友圈发赞助，不参与拉票，甚至只想用QQ(　ﾟ 3ﾟ)

**Comment by TransparentLC** [comment]
7.x 版界面加了，选择“使用 7.0 以上版本白色界面”就可以了(　ε:)

![](https://user-images.githubusercontent.com/47057319/70218806-a92f7800-177e-11ea-9b00-6ee95bdfe7bd.png)

我自己现在仍然没有在用 7.x 版，只是参考了其他截图的颜色和小图标，所以和实际可能会有差别～
