### ISSUE TITLE
一个搬运且盈利的网站

### ISSUE THREAD

**Issue by wulnm** [TransparentLC/WechatMomentScreenshot#30]
百度搜索"朋友圈集赞", 第一个就是[搬运的网站](https://www.41661.com/)

这个网站他**挂上了自己的赞赏码, 去掉了github的连接**

**Comment by TransparentLC** [comment]
甚至还加了个百度推送和统计……

我也没有什么办法，不过这网站引用的 JS 还是这边的，只能改一改 JS 把这网站拉黑了 ┐(´-｀)┌
