### ISSUE TITLE
换行处出现括号加年份区间会乱码，例如(2000-2019)这类的

### ISSUE THREAD

**Issue by qzl1120** [TransparentLC/WechatMomentScreenshot#32]
获取文章标题之后，如果文章的题目在换行处出现括号的话会有乱码，括号里面的内容都是年份区间的，例如：(2000-2019)

**Comment by TransparentLC** [comment]
有可以测试的公众号文章地址吗？

**Comment by qzl1120** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        
            
        
    
    
        
            https://mp.weixin.qq.com/s/BUlVfewBWClRRwdp00xgZA 
        
    https://mp.weixin.qq.com/s/Al1NR7t8X31KEWBlRD0AjQ 这两个链接都存在这样的现象，麻烦您看一下，以前没出现过这个问题。感激不尽
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                qianzhiling1995
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年6月22日 ***@***.***> 写道： 




有可以测试的公众号文章地址吗？



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by TransparentLC** [comment]
![](https://user-images.githubusercontent.com/47057319/122892573-1530fb80-d378-11eb-83bb-e3eb031969d5.png)
![](https://user-images.githubusercontent.com/47057319/122892608-1c580980-d378-11eb-8a44-22a99989ac1e.png)
获取的标题和生成的截图都是正常的……

**Comment by qzl1120** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        您好，我这里一直是这样的
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                qianzhiling1995
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年6月22日 ***@***.***> 写道： 








获取的标题和生成的截图都是正常的……



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by TransparentLC** [comment]
暂时先 Open，看看还有没有人碰到类似的问题。

**Comment by qzl1120** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        好滴，无比感谢大佬！！
        
    
        
            
        
    
    
     
    
        
                    
            
                
                    
                            
                                
                            
                            
                                qianzhiling1995
                            
                    
                        
                            
                                    ***@***.***
                            
                        
                
            
        
        
    
    
        签名由
        网易邮箱大师
        定制
    
 

    在2021年6月22日 ***@***.***> 写道： 




暂时先 Open，看看还有没有人碰到类似的问题。



—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.
