### ISSUE TITLE
刚刷到，没懂是干嘛用的，就是生成一张假截图？

### ISSUE THREAD

**Issue by muyufan** [TransparentLC/WechatMomentScreenshot#34]
别个既然要求转发，那肯定要去你朋友圈看你有没有转发啊

**Comment by FE-ng** [comment]
有的商家可能会有集赞的活动，而且这种有的是不会加你微信的（就算商家要求加我们可能也不会允许）。这个时候就是有用的了。

**Comment by A13437858** [comment]
还有一些公众号拿资源要你发朋友圈挂一天还要不能屏蔽任何人的，这个时候就会很有用
