### ISSUE TITLE
夸克浏览器和VIA浏览器无法正常保存

### ISSUE THREAD

**Issue by drpasserby** [TransparentLC/WechatMomentScreenshot#39]
电脑可以另存为，手机不行，但是可以通过浏览器自带的分享功能分享出去然后再保存。

**Comment by Adkimsm** [comment]
额，夸克不知道，但via的内核是webview，你更新webview试试

**Comment by Adkimsm** [comment]
[Auto reply] Hello, I have something to do at the moment, I will deal 
with it later, please leave a message if you have anything need me.
