### ISSUE TITLE
关于时间的细节和加入评论功能

### ISSUE THREAD

**Issue by fatmanhappycode** [TransparentLC/WechatMomentScreenshot#4]
时间的话会写”昨天21:03”而不是xx年xx月xx日
以及有一些赞助需要有评论，能不能加入评论功能呢
谢谢阿肥(=ﾟωﾟ)=

**Comment by TransparentLC** [comment]
时间的问题已经修复了√
评论功能之后我也会加上的……吧(=ﾟωﾟ)=

**Comment by TransparentLC** [comment]
在截图中自定义评论的功能已经加上了((꜆꜄•௰•)꜆꜄꜆
如果用起来没问题的话就可以关掉这个 issue 啦～

**Comment by fatmanhappycode** [comment]
太棒了！谢谢阿肥(〃∀〃)

**Comment by polgry** [comment]
当天时间应该是“1小时以前”这样，  现在是显失具体时间，这边能不能优化一下呢嘤嘤

**Comment by TransparentLC** [comment]
“X 小时以前”是按时间查看所有人的朋友圈时才会出现的，如果是点开某个人的朋友圈查看某条的话确实是显示具体时间，生成的截图是后者。
