### ISSUE TITLE
增加主流机型界面

### ISSUE THREAD

**Issue by WSure00** [TransparentLC/WechatMomentScreenshot#42]
作者您好，您的工具对我的帮助很大。我有一个小小的建议，就是可以选择主流的机型，比如说iPhone和华为小米等。安卓手机因为主题的原因，我觉得做标准的就可以，iPhone的话，添加全面屏和非全面屏就可以。感谢您！

**Comment by TransparentLC** [comment]
实际上这个标题栏是照着 [Android Oreo (8.x) 的样式](https://zh.wikipedia.org/wiki/File:Android_Oreo_8.1_screenshot.png)做的，原生 Android 应该算是“标准”了吧 2333

因为我不使用 iPhone 所以暂时不考虑加入 iOS 的标题栏，当然如果有人愿意帮忙实现然后提一个 PR 我一定是资辞的。除此之外，README 里也写了：

> ### 为什么生成的截图和我在手机上截的不一样？能不能做出 iOS 的样式？
>
> 不同手机的界面总是有那么一点区别的，要和真正的截图完全一样……我也很难办啊！（摊手）
> 
> 如果实在是很在意通知栏的样式的话，**可以从自己的手机上截一个通知栏的图然后覆盖上去……**

**Comment by TransparentLC** [comment]
最近添加了可以选择使用 iOS 的通知栏，不过因为我没有实机，所以只能参考网上找到的截图来做，不一定能做到完全一样……
