### ISSUE TITLE
报错

### ISSUE THREAD

**Issue by qqq-alt** [TransparentLC/WechatMomentScreenshot#44]
![df5702d9f85aadac3ff14ddd371285f](https://user-images.githubusercontent.com/60455952/141806251-c7dea9b6-52f5-4ea8-b965-312c10a4f1a0.jpg)
你好，我发现输入链接自动获取标题时经常会报错“无法连接到服务器”，而这个问题不出现时生成图片就会报错说RangeError: Maximum call stack size exceeded.

**Comment by TransparentLC** [comment]
可能是 html2canvas 的问题……有可以稳定触发的办法吗？

**Comment by qqq-alt** [comment]
我发现原因可能是我关闭页面和刷新较少导致数据积累，因为在我选择“清除保存的数据信息”后就能正常使用了。
感谢您的回复！

发自我的iPhone


------------------ 原始邮件 ------------------
发件人: ✨小透明・宸✨ ***@***.***&gt;
发送时间: 2021年11月24日 00:02
收件人: TransparentLC/WechatMomentScreenshot ***@***.***&gt;
抄送: qqq-alt ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [TransparentLC/WechatMomentScreenshot] 报错 (Issue #44)





 
可能是 html2canvas 的问题……有可以稳定触发的办法吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
