### ISSUE TITLE
强烈建议评论 功能添加随机姓名个头像的功能

### ISSUE THREAD

**Issue by ARC-MX** [TransparentLC/WechatMomentScreenshot#45]
强烈建议评论 功能添加随机姓名个头像的功能，一个一个填简直太难受了，我不大会该js代码，所以拜托各位了

**Comment by TransparentLC** [comment]
虽然可以从点赞的那堆头像里随机抽，不过因为我没有对头像分类，所以要是随机到一个二次元头像但是名字写着“○经理”那就有点尴尬了😂
&nbsp;
那么有什么随机生成姓名的工具/资料可以推荐吗？（faker.js好像太重了）



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月26日(星期五) 下午5:46
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [TransparentLC/WechatMomentScreenshot] 强烈建议评论 功能添加随机姓名个头像的功能 (Issue #45)




 
强烈建议评论 功能添加随机姓名个头像的功能，一个一个填简直太难受了，我不大会该js代码，所以拜托各位了

**Comment by TransparentLC** [comment]
已添加，现在点击“添加评论”时会默认随机生成一个名字并抽取一个头像。

由于 jsDelivr 缓存的关系，也许需要过几天才会应用更新后的 JS。

**Comment by ARC-MX** [comment]
优秀



Best regards

ARCW    ​Wang MengXuan





Email: ***@***.***





---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2021年12月07日 19:42 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.******@***.***> |
| 主题 | Re: [TransparentLC/WechatMomentScreenshot] 强烈建议评论 功能添加随机姓名个头像的功能 (Issue #45) |

已添加，现在点击“添加评论”时会默认随机生成一个名字并抽取一个头像。

由于 jsDelivr 缓存的关系，也许需要过几天才会应用更新后的 JS。
