### ISSUE TITLE
建议增加 视频号转发界面

### ISSUE THREAD

**Issue by meisa233** [TransparentLC/WechatMomentScreenshot#46]
![QQ图片20211206210209](https://user-images.githubusercontent.com/39454391/144850823-5ca75aa2-7f0f-48a6-9c5f-63221cdb6ac8.jpg)
类似这种东西
公司总是提各种各样奇怪的要求 希望大佬考虑一下

**Comment by TransparentLC** [comment]
其实就是多了个中间的播放图标而已？

我这里有个[播放图标](https://svgur.com/s/cZ8)，可以先用各种图片编辑器加到视频截图的中间。

也许之后也会在工具里加上添加这个图标的功能……

**Comment by meisa233** [comment]
> 其实就是多了个中间的播放图标而已？
> 
> 我这里有个[播放图标](https://svgur.com/i/cZ8.svg)，可以先用各种图片编辑器加到视频截图的中间。
> 
> ![](https://camo.githubusercontent.com/d230cbf54ee63bd45375c489b4d97bce5842af57ebb1f75be75c1087bbe9fcdc/68747470733a2f2f73766775722e636f6d2f692f635a382e737667)
> 
> 也许之后也会在工具里加上添加这个图标的功能……

感谢大佬回复，除了那个视频的截图，可能还需要有个视频号·视频来源的（自定义标识）

**Comment by TransparentLC** [comment]
已添加，现在生成带有单张图片（这个时候就可以使用视频截图了）的时候可以选择在中间加上那个播放图标，另外在“转发出处”中输入“视频号 · ○○○”就会在那个位置以蓝字显示了（其他情况下是和左边的时间相同的灰色）。

![](https://user-images.githubusercontent.com/47057319/145023023-38fa8bce-da64-48db-b3bd-32f6feb3556e.png)

由于 jsDelivr 缓存的关系，也许需要过几天才会应用更新后的 JS。

**Comment by meisa233** [comment]
> 

感谢大佬，大佬喝阔乐

**Comment by meisa233** [comment]
> 已添加，现在生成带有单张图片（这个时候就可以使用视频截图了）的时候可以选择在中间加上那个播放图标，另外在“转发出处”中输入“视频号 · ○○○”就会在那个位置以蓝字显示了（其他情况下是和左边的时间相同的灰色）。
> 
> ![](https://user-images.githubusercontent.com/47057319/145023023-38fa8bce-da64-48db-b3bd-32f6feb3556e.png)
> 
> 由于 jsDelivr 缓存的关系，也许需要过几天才会应用更新后的 JS。

感谢大佬更新的新功能，不过看上去那个视频号 · 的字的颜色还是灰色？可能是没更新JS的缘故？

**Comment by TransparentLC** [comment]
在 JS 的链接上加了个 `@latest`，现在应该是最新的了。

有人说使用 purge.jsdelivr.net 可以强制刷新，不过实际上据我实测还是要等短则一两天长则一个多星期的时间……
