### ISSUE TITLE
设定点赞数但是生成的图片中没有赞

### ISSUE THREAD

**Issue by DF-18** [TransparentLC/WechatMomentScreenshot#47]
https://akarin.dev/WechatMomentScreenshot/

我在这里尝试生成图片，设定10个点赞数，但是生成的图片里没有赞，请问大神什么原因呀

**Comment by TransparentLC** [comment]
F12 打开调试工具然后检查一下 Console 和 Network 里有没有生成截图时头像加载失败之类的提示？另外我这里使用没有问题……

（如果是在手机上的话，可以从 `https://akarin.dev/WechatMomentScreenshot/?debug` 打开，用右下角的灰色齿轮图标打开虚拟调试工具）

**Comment by huangchaoqun** [comment]
![image](https://user-images.githubusercontent.com/24500684/168515069-7a65c02c-bf97-4f12-9211-0c284e815415.png)
头像图片获取失败哦

**Comment by huangchaoqun** [comment]
知道了，挂代理解决
