### ISSUE TITLE
怎么修改源码呀？

### ISSUE THREAD

**Issue by HapCoderWei** [TransparentLC/WechatMomentScreenshot#48]
前端小白想自己改下样式学习，但是发现修改index.src.html不能直接生效，要修改index.html才能真正生效。但是默认index.html好像是没有格式化的，看起来像是自动生成的文件。
想问下是通过什么方式或工具将index.src.html导出成index.html的吗？求指教，谢谢

**Comment by TransparentLC** [comment]
这个操作是前端资源压缩（比如各种 *.min.js 和 *.min.css），可以稍微减少一些文件大小。
相关的常用工具：html-minifier、terser、clean-css...



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年2月4日(星期五) 下午2:50
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [TransparentLC/WechatMomentScreenshot] 怎么修改源码呀？ (Issue #48)




 
前端小白想自己改下样式学习，但是发现修改index.src.html不能直接生效，要修改index.html才能真正生效。但是默认index.html好像是没有格式化的，看起来像是自动生成的文件。
 想问下是通过什么方式或工具将index.src.html导出成index.html的吗？求指教，谢谢

**Comment by HapCoderWei** [comment]
明白啦，已经学会怎么用了，我的用法是`html-minifier-terser --collapse-whitespace --remove-comments --minify-js true index.src.html > index.html`，试了可以使用，多谢指导，请你喝杯奶茶👍
