### ISSUE TITLE
无法获取公众号链接的封面图

### ISSUE THREAD

**Issue by yanglei2333** [TransparentLC/WechatMomentScreenshot#50]
可以获取标题，但是封面图无法获取

**Comment by 1010BYang** [comment]
+1，我也遇到这样的问题

**Comment by TransparentLC** [comment]
请提供公众号文章链接，另外这个问题是随机出现还是必定出现？

**Comment by allenrong88** [comment]
不知道小红书的链接能不能获取？

**Comment by TransparentLC** [comment]
请提供链接示例和转发效果。

我目前知道的链接格式应该是 `^https:\/\/www\.xiaohongshu\.com\/explore\/[\da-f]{24}$`。
