### ISSUE TITLE
朋友这个项目好像被拼多多无良商家拿过去卖了

### ISSUE THREAD

**Issue by Pigrey** [TransparentLC/WechatMomentScreenshot#51]
rt，一个卖9.9，已经卖了4k多份了。金额不小，建议起诉了。
店铺链接：
https://mobile.yangkeduo.com/goods2.html_wvx=10&refer_share_uin=JAOKXYMYRS2LNCFUMNGQCZBBMI_GEXDA&refer_share_uid=7601970121&share_uin=JAOKXYMYRS2LNCFUMNGQCZBBMI_GEXDA&page_from=101&_wv=41729&refer_share_id=3iLILhZWMgW9FaPeEOsU18F9waBsXa2H&refer_share_channel=copy_link&share_uid=7601970121&pxq_secret_key=UTEHB53JUYXRGTG3OSORQTSIOCXMQIOKXFKSVJSI5CX2RMHOWYAA&goods_id=251757519617

**Comment by TransparentLC** [comment]
“商品不存在”
