### ISSUE TITLE
建议添加随机头像和ID功能

### ISSUE THREAD

**Issue by h9292** [TransparentLC/WechatMomentScreenshot#53]
建议添加随机头像和ID功能

**Comment by TransparentLC** [comment]
在[这个 Commit](https://github.com/TransparentLC/WechatMomentScreenshot/commit/565427a6bef5baf231b0a47ac14e08b0447be6c8) 里已经做了添加评论的时候默认使用随机头像和名字的功能。

**Comment by h9292** [comment]
主要是可以不用自己上传头像和名字就更好了 XP



在 2022-05-01 19:15:33，"✨小透明・宸✨" ***@***.***> 写道：

在这个 Commit 里已经做了添加评论的时候默认使用随机头像和名字的功能。
