### ISSUE TITLE
点赞人头像能不能选择，或者自己提供上传，根据点赞数补充获取之类的...

### ISSUE THREAD

**Issue by zhaoxny** [TransparentLC/WechatMomentScreenshot#56]
生成好几张类似的图，点赞头像重复率太高了

**Comment by TransparentLC** [comment]
一个个添加头像也会很麻烦的，所以并不打算加入这个功能，以及只能保证生成单张截图时在把头像库抽完之前不会重复……

如果有什么可以快速爬取大量头像的途径的话倒是可以用来充实头像库。
