### ISSUE TITLE
页面css失效了，看报错好像是引用的css文件和js文件失效了

### ISSUE THREAD

**Issue by HapCoderWei** [TransparentLC/WechatMomentScreenshot#57]
麻烦看下是不是cdn上面的文件失效了呀，现在打开页面没有样式了
<img width="1015" alt="截屏2022-05-16 18 26 19" src="https://user-images.githubusercontent.com/6915031/168573221-f92d1063-d243-4207-a178-6be0113d44dc.png">

**Comment by itsHenry35** [comment]
jsdelivr is under dns hijacking in china [https://github.com/jsdelivr/jsdelivr/issues/18397](jsdelivr issue)

**Comment by TransparentLC** [comment]
改成使用 unpkg 和直接从 GitHub Pages 加载各种 CSS 和 JS 了，GFW 整天没事就墙这个污染那个确实有够烦的……
