### ISSUE TITLE
help

### ISSUE THREAD

**Issue by remoonay** [TransparentLC/WechatMomentScreenshot#58]
生成失败
SecurityError: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.

Error: Failed to execute 'toDataURL' on 'HTMLCanvasElement': Tainted canvases may not be exported.
    at https://fastly.jsdelivr.net/combine/npm/html2canvas@1/dist/html2canvas.min.js,npm/mdui@1/dist/js/mdui.min.js,gh/TransparentLC/WechatMomentScreenshot@latest/main.min.js:46:23294
什么问题啊大佬

**Comment by TransparentLC** [comment]
提供一下生成截图之前的操作过程？

**Comment by seeyou-ctrip** [comment]
是我的打开方式不对吗，双击index.html我就打开运行了，是还有什么其他的操作吗

**Comment by TransparentLC** [comment]
要起一个 HTTP 服务才行，直接双击是不行的……

有 Python 的话在 repo 的目录打开终端然后 `python -m http.server`，没有的话也可以下一个 [miniserve](https://github.com/svenstaro/miniserve) 然后 `miniserve . --index index.html`。

**Comment by seeyou-ctrip** [comment]
> 

好的 谢谢大佬
