### ISSUE TITLE
镜像站申请

### ISSUE THREAD

**Issue by drpasserby** [TransparentLC/WechatMomentScreenshot#59]
网址：[微信朋友圈转发截图生成工具（镜像）](https://my.wulvxinchen.cn/makewechat/)
原网址已经收录进自己的工具站：[心尘工具集](https://my.wulvxinchen.cn/tools/)

**Comment by TransparentLC** [comment]
已在 README.md 中添加～

**Comment by TransparentLC** [comment]
由于最近我这里为了添加一些功能而进行了更新，刚刚看了一下当时你部署的源代码已经不能正常使用了，如果想要继续部署的话可以重新下载代码～

**Comment by drpasserby** [comment]
感谢提醒，已经更新了镜像网站部署的代码~也感谢作者的辛勤开发~
