### ISSUE TITLE
缺少运营商 信息还有4G什么的 

### ISSUE THREAD

**Issue by linuxresearch** [TransparentLC/WechatMomentScreenshot#6]

**Comment by TransparentLC** [comment]
也不是所有人的手机都会把运营商显示在通知栏的，另外那个直角三角形其实就是 Material Design 下的手机信号的图标 ( ﾟ∀。)

因为大家的手机使用的主题不同，iOS 和 Android 的界面也有不同，全部适配的话就会很麻烦。如果确实需要通知栏和实机一样的话，可以自己截了通知栏的图再覆盖上去～
