### ISSUE TITLE
哥您好，能把我域名添加到白名单吗，非常感谢！

### ISSUE THREAD

**Issue by Allenorz** [TransparentLC/WechatMomentScreenshot#60]
https://www.wanshiwutool.cn/
会按照您的要求来二次部署的，非常感谢！

**Comment by TransparentLC** [comment]
已经在获取标题封面图的 API 的 `Access-Control-Allow-Origin` 以及 README 里加上这个域名了～

**Comment by TransparentLC** [comment]
由于最近我这里为了添加一些功能而进行了更新，刚刚看了一下当时你部署的源代码已经不能正常使用了，如果想要继续部署的话可以重新下载代码～

**Comment by Allenorz** [comment]
收到了，非常感谢
