### ISSUE TITLE
关于右上角时间显示

### ISSUE THREAD

**Issue by Auunes** [TransparentLC/WechatMomentScreenshot#61]
当开启评论区时，截图右上角的时间应该要改成最后一个人评论的时间，而不是发布朋友圈时的时间

**Comment by TransparentLC** [comment]
可以自己在“截图日期”那里修改右上角的时间。

**Comment by Auunes** [comment]
> 可以修改自己的日期”，在上面的“时间截图”。

谢谢，是我眼瞎了qwq
