### ISSUE TITLE
获取随机头像失败

### ISSUE THREAD

**Issue by LaLaLaLou** [TransparentLC/WechatMomentScreenshot#62]
![image](https://user-images.githubusercontent.com/35133759/188411443-926c307c-1a07-4854-ac62-0b2f46590cd3.png)

**Comment by yqs9807** [comment]
挂代理解决

**Comment by qxj** [comment]
> 挂代理解决

部分图源失效了，返回403错误。比如：`https://legacy-pics.meiqiausercontent.com/images/czE6pTLG/nnI7/huKt6QianqR8NJczPCT9.jpg`

<img width="458" alt="image" src="https://user-images.githubusercontent.com/225400/217798851-914cb344-72fd-4b64-b877-e3e31c2670c6.png">

**Comment by yqs9807** [comment]
> https://legacy-pics.meiqiausercontent.com/images/czE6pTLG/nnI7/huKt6QianqR8NJczPCT9.jpg

我挂了一个香港的VPN，可以打开这个图像。好像https://legacy-pics.meiqiausercontent.com/images/*墙了国内，都得通过挂代理来解决
![image](https://user-images.githubusercontent.com/29301775/217799879-391b9417-737f-4b8a-aa6b-224b148e6409.png)

**Comment by TransparentLC** [comment]
稍后我尝试迁移一下这堆图片吧……
确实也不是第一次因为第三方图床而翻车了( ´_っ`)

**Comment by TransparentLC** [comment]
迁移完了，顺便加了个“自定义头像库”的设定，其实就是把所有头像的 URL 放进一个文本文档里，加载这个文档后就可以从里面的头像随机抽取了。

于是我弄了两个头像库，都放在我的服务器上，应该不会翻车，真的翻车了的话换源也会很简单：

* 默认的头像库，从我的服务器加载，因为用了 Cloudflare 所以在墙内加载速度可能较慢：https://i.akarin.dev/wms-avatar/avatar-stable.txt
* 和之前一样上传到图床，加载速度较快：https://i.akarin.dev/wms-avatar/avatar-fast.txt

于是根据自己的需求自定义截图中出现的头像也是可行的了，比如自己收集统一某种风格的头像然后把头像库上传到自己的服务器上什么的……
