### ISSUE TITLE
大佬还更新不

### ISSUE THREAD

**Issue by Lmy-696** [TransparentLC/WechatMomentScreenshot#64]
微信又对界面进行了些调整，还会更新界面吗，还有能不能加个纯点赞数的那个页面

**Comment by TransparentLC** [comment]
不知道这个“调整”指的是什么，毕竟我自己用的微信是旧版而且非必要不更新……

“能不能加个纯点赞数的那个页面” 没有添加其他界面的打算。

**Comment by YRHONG-02** [comment]
@TransparentLC 大佬好，通知栏可以截屏拼接，但存在一些细节不同(也可能和微信版本和手机机型有关)：①评论区框框左上角不该有一个突出；②转发时间应该是灰色而不是蓝色的字体；③文本和微信昵称字体大小不对。麻烦大佬过目，也感谢大佬制作出这个工具 ！

**Comment by YRHONG-02** [comment]
@TransparentLC 抱歉，②没有问题，也就是①和③(比如微信昵称要加粗，另外“转发时间”和“删除”之间的距离较宽)，嘿嘿打扰大佬了

**Comment by YRHONG-02** [comment]
好嘞！！谢谢大佬！！




Yrh
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "TransparentLC/WechatMomentScreenshot"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年3月13日(星期一) 晚上10:59
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [TransparentLC/WechatMomentScreenshot] 大佬还更新不 (Issue #64)





 
@YRHONG-02 这几个已经改了，左上角的突出应该是 8.0 开始去掉的，“转发时间”和“删除”之间的距离我目测了一下大概是两个数字（一开始写的时候还是一个数字来着），所以把这两个之间的空格数量从两个变成了四个。
