### ISSUE TITLE
提交镜像站，希望可以加入白名单

### ISSUE THREAD

**Issue by jinzi1007** [TransparentLC/WechatMomentScreenshot#65]
镜像站：https://quziyuan.cn/zhuanti/zhuanfa

想使用公众号文章封面提取功能，希望可以给加入白名单。

自己搭建了一个get_article_info.php，但是不能返回封面图地址，应该上传步骤接口出现问题。把图片上传步骤代码删除后，可以直接输出公众号封面官方链接。也希望博主可以修复一下。

**Comment by TransparentLC** [comment]
已添加。

`get_article_info.php` 这个稍微等一下……这个文件好久没动过了，里面用的上传接口早就失效了。原图的链接因为没有 CORS 的响应头所以并不能直接使用。

**Comment by TransparentLC** [comment]
由于最近我这里为了添加一些功能而进行了更新，刚刚看了一下当时你部署的源代码已经不能正常使用了，如果想要继续部署的话可以重新下载代码～
