### ISSUE TITLE
用户名能不能随机呢

### ISSUE THREAD

**Issue by Laotu66** [TransparentLC/WechatMomentScreenshot#68]
如题，用户名是否可以随机

**Comment by TransparentLC** [comment]
如果是评论的用户名的话，在添加的时候会随机生成一个。

如果是发送朋友圈的用户名的话，把这个随机的用途是什么？

**Comment by Laotu66** [comment]
> 如果是评论的用户名的话，在添加的时候会随机生成一个。
> 
> 如果是发给朋友圈的用户名的话，把这个随机的用户名是什么？

比如某个微信内容，要求大家转发后截图，如果通过咱们这个去转发，需要发朋友圈的用户名和头像随机，右上角时间也随机，就这个意思

**Comment by TransparentLC** [comment]
考虑到这个功能的使用场景可能超过了“个人应付各类强制要求转发朋友圈”的使用范围，甚至有便于批量生成截图的可能，我暂时不会考虑添加这个功能。

**Comment by Laotu66** [comment]
> 考虑到这个功能的使用场景可能超过了“个人应付各类强制要求转发朋友圈”的使用范围，甚至有便于批量生成截图的可能，我暂时不会考虑添加这个功能。

能定制吗？工作需要WeChat：732382715
