### ISSUE TITLE
时间和ui问题

### ISSUE THREAD

**Issue by hackermengzhi** [TransparentLC/WechatMomentScreenshot#69]
1、截图日期和发文日期在同一天现在已经是类似于xxx时间前（1分钟前）
2、建议点赞数量修改为每行7个（iphone数字标准版大小）

**Comment by TransparentLC** [comment]
> 1、截图日期和发文日期在同一天现在已经是类似于xxx时间前（1分钟前）

刚刚测试了一下，在我用的 Android 微信 8.0.21 上并没有这个更改。

![IMG_20230512_144532](https://github.com/TransparentLC/WechatMomentScreenshot/assets/47057319/0416da6f-7447-4b3a-9cf0-618ac1d1b751)

> 2、建议点赞数量修改为每行7个（iphone数字标准版大小）

实际上就算是 iPhone 的话一行的点赞数也是不一样的，比如在我能找到的 iPhone 的截图里一行七个（[例](http://upload.techweb.com.cn/imgs/2023/0414/1681438980122.jpg)）和八个（[例 1](https://img2.baidu.com/it/u=2112426593,3143672274&fm=253)、[例 2](https://img2.baidu.com/it/u=3236164013,1543124124&fm=253)、[例 3](https://img.lancdn.com/landian/2020/08/78618.png)）的情况都有，而我这里就是一行九个了。总之这是个根据机型分辨率缩放等等不同而不一样的东西，请参见 README 的“为什么生成的截图和我在手机上截的不一样？”的第一行（逃

**Comment by hackermengzhi** [comment]
抄收了，感谢。另外希望点赞的头像也可以添加自定义功能（逃

从 Windows 版邮件发送

发件人: ✨小透明・宸✨
发送时间: 2023年5月12日 15:04
收件人: TransparentLC/WechatMomentScreenshot
抄送: BUG设计工程师; Author
主题: Re: [TransparentLC/WechatMomentScreenshot] 时间和ui问题 (Issue #69)

1、截图日期和发文日期在同一天现在已经是类似于xxx时间前（1分钟前）
刚刚测试了一下，在我用的 Android 微信 8.0.21 上并没有这个更改。

2、建议点赞数量修改为每行7个（iphone数字标准版大小）
实际上就算是 iPhone 的话一行的点赞数也是不一样的，比如在我能找到的 iPhone 的截图里一行七个（例）和八个（例 1、例 2、例 3）的情况都有，而我这里就是一行九个了。总之这是个根据机型分辨率缩放等等不同而不一样的东西，请参见 README 的“为什么生成的截图和我在手机上截的不一样？”的第一行（逃

**Comment by TransparentLC** [comment]
其实现在靠设定那个“自定义头像库”已经可以自定义了……但是毕竟还需要自己进行上传图片和带有这些图片的链接的文件的操作，对程序员以外的用户不是很方便，一开始没考虑添加这个是估计手动一个个添加图片会累死所以应该不会有这个需求的（

等我哪天重写的话说不定会考虑这个，但是那就是有生之年了，或者以后再想想有没有别的实现方法（逃

**Comment by hackermengzhi** [comment]
ios已做更改 截图如下

------------------ 原始邮件 ------------------
发件人: ✨小透明・宸✨ ***@***.***&gt;
发送时间: 2023年5月12日 15:04
收件人: TransparentLC/WechatMomentScreenshot ***@***.***&gt;
抄送: BUG设计工程师 ***@***.***&gt;, Author ***@***.***&gt;
主题: Re: [TransparentLC/WechatMomentScreenshot] 时间和ui问题 (Issue #69)





  
1、截图日期和发文日期在同一天现在已经是类似于xxx时间前（1分钟前）
  
刚刚测试了一下，在我用的 Android 微信 8.0.21 上并没有这个更改。
 

  
2、建议点赞数量修改为每行7个（iphone数字标准版大小）
  
实际上就算是 iPhone 的话一行的点赞数也是不一样的，比如在我能找到的 iPhone 的截图里一行七个（例）和八个（例 1、例 2、例 3）的情况都有，而我这里就是一行九个了。总之这是个根据机型分辨率缩放等等不同而不一样的东西，请参见 README 的“为什么生成的截图和我在手机上截的不一样？”的第一行（逃
