### ISSUE TITLE
点赞列表少了一列

### ISSUE THREAD

**Issue by WainWong** [TransparentLC/WechatMomentScreenshot#7]
![Inked下载_LI](https://user-images.githubusercontent.com/27768275/80669662-8e67f200-8ad7-11ea-95c1-1d32ad68e276.jpg)
点赞列表最右边有一列空白的，希望有空可以修复一下，谢谢！~

**Comment by TransparentLC** [comment]
已修复～
![批注 2020-04-30 200207](https://user-images.githubusercontent.com/47057319/80708084-9fd3ed00-8b1d-11ea-97bf-841247f9aacc.png)

**Comment by WainWong** [comment]
老哥效率真高啊👏

✨小透明・宸✨ <notifications@github.com> 于 2020年4月30日周四 20:03写道：
