### ISSUE TITLE
朋友圈文字中含有一些数字或者月份等图片符号，会丢失

### ISSUE THREAD

**Issue by tdsxdtdg** [TransparentLC/WechatMomentScreenshot#70]
![1](https://github.com/TransparentLC/WechatMomentScreenshot/assets/133933712/7eed8f7b-d4c3-4ae3-828a-b446040a614e)
![2](https://github.com/TransparentLC/WechatMomentScreenshot/assets/133933712/69dae895-6bcc-4c45-87ae-243010b343c9)

**Comment by TransparentLC** [comment]
所以这种营销文案好好的文字不用偏要用 emoji 是哪来的风气……从抽象话那边学的吗（

其实不是这个工具的问题，而是在这些软件中复制消息时**很多常用的 emoji 根本没有以标准的 Unicode 字符的形式被复制下来**。这么做我估计是为了使全平台都能**按照 Apple 的那套样式**显示 emoji。现在各个系统都自带了 emoji 字体，不过显示出来的样子并不一样，为什么一定要统一用 Apple 那套我暂且蒙在鼓里。

临时去沙盒里装了个电脑版微信来演示一下，复制一条带 emoji 的消息，再找个[剪贴板查看器](https://github.com/walterlv/ClipboardViewer)看看剪贴板里的原始内容：

![](https://github.com/TransparentLC/WechatMomentScreenshot/assets/47057319/e7aa0111-24c8-4028-a80e-b868f36ba367)

只有🌶️使用了系统自带的 emoji 字体显示并且正常地以纯文本格式（UnicodeText）被复制了。为什么在微信和隔壁的 QQ 里复制粘贴这些带 emoji 的消息就没有问题呢？因为还复制了 WeChat_RichEdit_Format 和 QQ_Unicode_RichEdit_Format 这两种专有的格式，当然其他软件就不认得了。

所以有两种办法：

* **别用那些花花绿绿的 emoji 了**，直接写“√ 订购1年 立减200元+送1个月奶”这样的纯文本。
* 去 [Emojipedia](https://emojipedia.org/) 这样的网站，一个个搜索你要用的 emoji，然后**复制粘贴它们的 Unicode 字符**。当然这样操作的话生成截图的时候使用的是系统自带的 emoji 字体而不是 Apple 那套，可能会有人在意这个区别。

![](https://github.com/TransparentLC/WechatMomentScreenshot/assets/47057319/241ce69b-1ad7-4d95-b2d8-713db31061ae)
