### ISSUE TITLE
ios截图左右方向上是1280像素

### ISSUE THREAD

**Issue by hello147** [TransparentLC/WechatMomentScreenshot#75]
IOS截图左右方向上是1280像素，当前默认是1080，做出来总是感觉不一样，作者可以改一下

**Comment by TransparentLC** [comment]
> ## 为什么生成的截图和我在手机上截的不一样？能不能做出 iOS 的样式？
> 不同手机的界面总是有那么一点区别的，要和真正的截图完全一样……我也很难办啊！（摊手）
> ……
> 因为我并没有 iOS 设备，所以只能参考网上找到的截图来写样式，**不一定能做到和实机一样**。

总之就是众口难调，如果有人能帮忙完善 iOS 的样式当然是好的，但是大概是没有的。
