### ISSUE TITLE
国人的repo就是牛逼

### ISSUE THREAD

**Issue by xx10n31y** [TransparentLC/WechatMomentScreenshot#79]
在explorer看到, 什么叫除代码之外的不要fork, 国人的repo就是牛逼. 你这么牛逼, 应该开private repo, 傻卵

**Comment by TransparentLC** [comment]
虽然语气很不友善，不过既然问到这个的话想了想还是应该解释一下。

> “在开源项目中，分支常用于迭代想法或更改，然后将其合并到上游存储库。”
>
> [关于分叉 - GitHub 文档](https://docs.github.com/zh/pull-requests/collaborating-with-pull-requests/working-with-forks/about-forks)

Fork 的作用是让你可以在已有 repo 的基础上添加新功能、修复 bug 等等，也有可能是因为原作者停止维护或理念不合等原因而 fork 出来作为新的项目继续发展，本质上其实都是用来**贡献代码**的，可以把自己的修改反馈到上游不过这个也是可选的。

但是实际上有很多人**把 fork 误用成了收藏**，比如有些 fork 这个 repo 的用户我点进去一看发现有数十成百上千个 repo，其中绝大部分都是 fork，几乎所有 fork 都是“This branch is up to date with ...”或者“This branch is ... commits behind ...”而不是“This branch is ... commits ahead of ...”，也就是说这些 fork 没有产生任何代码贡献。我暂且不知道这些用户这么做的意义。

更符合收藏用途的应该是 star，同时也可以作为对维护者的一种小小的鼓励，不愿意或不方便 star 的话使用浏览器的收藏夹/书签等等也是可以的。有些 repo 的用途是“fork 然后自行修改某些参数用来执行 GitHub Actions”，更适合这种情况的其实是把它作为 template repo。

我写上那句话只是为了提醒看到它的人，没有完全不允许 fork 的意思（即使 GitHub 真的允许这么做）。
