### ISSUE TITLE
选择自动获取公众号文章标题时出现“无法连接到服务器”的状况（已排查我这边的网络问题，用PC端，手机端（已用流量测试）均显示相通的状况）

### ISSUE THREAD

**Issue by sky-stars666** [TransparentLC/WechatMomentScreenshot#8]

**Comment by sky-stars666** [comment]
还或者显示“无法获取”的状况，总之就是获取失败……

**Comment by viewv** [comment]
同样遇到了这个问题

**Comment by TransparentLC** [comment]
页面的 HTML 源代码（里面的 JS 源代码）原来的公众号文章标题部分是 `var msg_title = "标题";`，现在改成了 `var msg_title = '标题'.html(false);`，这个我已经修复了～

但是“无法连接”是因为……我在自己的服务器上用了 Cloudflare 的~~云减速~~，结果现在解析到的 IPv4 地址是个已经被墙了的，我也很绝望啊 \_(:τ」∠)\_ 如果用手机流量的话有可能会解析到 IPv6 地址就可以正常使用。或者有没有人愿意把 [get_article_info.php](https://github.com/TransparentLC/WechatMomentScreenshot/blob/master/get_article_info.php) 部署到自己的服务器上……？

如果不得不手动获取的话，可以查看网页源代码（或者找个在线工具，比如[这个](http://mk.mkblog.cn/home/html.php)），然后在源代码里搜索 `var msg_title` 和 `var msg_cdn_url`，这两个就分别是标题和封面图 URL。

**Comment by viewv** [comment]
我这里测试应该没有问题了，非常感谢，计划迁移到自己的服务器了。

**Comment by TransparentLC** [comment]
在 Cloudflare Worker 上做了个简单的代理，应该可以解决后端被墙了的问题(=ﾟωﾟ)=

**Comment by sky-stars666** [comment]
好的，非常感谢，继续支持！Thanks♪(･ω･)ﾉ
