### ISSUE TITLE
网页分享、公众号文章一直显示获取失败！( ´_っ`) 无法连接到服务器。

### ISSUE THREAD

**Issue by szsyzx** [TransparentLC/WechatMomentScreenshot#9]
网页分享、公众号文章一直显示获取失败！( ´_っ`) 无法连接到服务器。

搭建在国外的服务器也是如此到底如何解决呢

求大佬给个解决办法

**Comment by TransparentLC** [comment]
目前获取标题和封面图的代码部署在 Cloudflare Workers 上，在国内大部分地区应该都能正常连接，如果确实不行的话请把[数据删除]批判一番（摊手

![](https://user-images.githubusercontent.com/47057319/83121239-a21d6d00-a104-11ea-81fe-cabfa4b4e2cd.png)

**Comment by szsyzx** [comment]
这个地址打的开的
 $ch = curl_init('https://kfupload.alibaba.com/mupload');

这个网址不存在啥情况啊，需要怎么弄啊

**Comment by TransparentLC** [comment]
这是个“图床”接口（？），只能用 POST 上传图片，直接打开的话没有什么东西也是正常现象嘛……┐(´-｀)┌

至于为什么需要一个“图床”，因为有防盗链所以不能直接把封面图的链接拿来用，以前就是用转存到图床的方式解决的。

**Comment by szsyzx** [comment]
郁闷了老大把您的源码部署再自己服务器死活显示链接到服务器失败，好难受啊。

**Comment by TransparentLC** [comment]
开 F12 看一下请求结果？我当时写的是状态码不是 200 就会提示“连接失败” |-` )（如果连接成功了但是返回的数据错误会有别的提示）

后端不是必须的，以及你也可以自己另外写一个这个后端的代码😂 URL 参数 `url` 是公众号文章的 URL，只要返回以下的 JSON 就可以了：

```json
{
    "success": true, // 是否请求成功
    "title": "震惊！世界最大同性交友网站被微软收购了！", // 公众号文章标题
    "cover": "https://mmbiz.qpic.cn/..." // 封面图 URL
}
```

**Comment by szsyzx** [comment]
老大有啥联系方式吗电报群也可以

**Comment by TransparentLC** [comment]
并没有……(='\_'=)

其实还有另外一个（应该是）比较稳定的接口也能实现获取标题和封面图，返回的字段和我这个稍微有一些不同，在发出请求的 JS 代码上改一改就可以用了。例子：https://www.135editor.com/downloads/getRemoteContent?uri=https://mp.weixin.qq.com/s/BrueoeY2Vb5LQYKWDFjo9g

**Comment by szsyzx** [comment]
老大可以建立个电报群啊方便聊天

**Comment by szsyzx** [comment]
发出请求的 JS是那个啊老大

**Comment by TransparentLC** [comment]
https://github.com/TransparentLC/WechatMomentScreenshot/blob/fd5ae900960a1415869a7b851125b728e5df6084/index.html#L795

**Comment by szsyzx** [comment]
老大在吗找您做个项目，也是朋友圈相关的

**Comment by szsyzx** [comment]
老大看到速度回话啊，我QQ：312781278

**Comment by TransparentLC** [comment]
我做这个工具也只是为了自用，并没有什么进一步的想法……

以及没什么别的问题的话这个我就先 close 了|-` )
